//! Notice of Electronic Filing (NEF) domain model
//!
//! This module defines types for generating and tracking Notices of
//! Electronic Filing, which are sent to case participants when a
//! document is filed via CM/ECF.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use uuid::Uuid;

/// Method by which a filing notice is delivered to a recipient
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum DeliveryMethod {
    /// Electronic notice via the CM/ECF system
    ElectronicNef,
    /// Paper copy mailed to the recipient
    PaperCopy,
}

/// A recipient of a Notice of Electronic Filing
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct NefRecipient {
    /// Name of the recipient (attorney or party)
    pub name: String,
    /// Email address for electronic notice delivery
    pub email: Option<String>,
    /// Method by which the notice was delivered
    pub delivery_method: DeliveryMethod,
    /// Timestamp when the notice was served to this recipient
    pub served_at: Option<DateTime<Utc>>,
}

/// A Notice of Electronic Filing generated by CM/ECF
///
/// This notice is generated automatically when a document is filed
/// electronically and serves as proof of service on all registered
/// CM/ECF participants.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct NoticeOfElectronicFiling {
    /// Unique identifier for the filing
    pub filing_id: Uuid,
    /// Case number in standard federal format (e.g., "1:24-cr-00123")
    pub case_number: String,
    /// Timestamp when the document was filed
    pub filed_at: DateTime<Utc>,
    /// Type of document that was filed
    pub document_type: String,
    /// Name of the person or entity that filed the document
    pub filer_name: String,
    /// Docket text describing the filing
    pub docket_text: String,
    /// List of recipients who received or will receive notice
    pub recipients: Vec<NefRecipient>,
}
