use spin_sdk::http::{IntoResponse, Params, Request, Response, ResponseBuilder};
use std::sync::Arc;
use url::Url;
use utoipa::openapi::ServerBuilder;
use utoipa::OpenApi;

/// Generate and return the OpenAPI specification for the ToDo API
///
/// This function dynamically generates the OpenAPI JSON specification,
/// including the appropriate server URL based on the runtime environment.
pub fn get_openapi_description(req: Request, _: Params) -> anyhow::Result<impl IntoResponse> {
    let mut openapi_description = OpenApiDocs::openapi();
    let (url, description) = get_server_info(&req);
    openapi_description.servers = Some(vec![ServerBuilder::new()
        .url(url)
        .description(Some(description))
        .build()]);

    Ok(ResponseBuilder::new(200)
        .header("content-type", "application/json")
        .body(openapi_description.to_pretty_json()?)
        .build())
}

/// Determine the server URL and description based on the runtime environment
///
/// Returns a tuple of (server_url, description) where the server URL
/// is dynamically determined based on whether the app is running locally
/// or in production.
fn get_server_info(req: &Request) -> (String, String) {
    match is_local_spin_runtime(&req) {
        true => {
            let full_url = req
                .header("spin-full-url")
                .expect("spin-full-url should be set when running api with spin CLI")
                .as_str()
                .expect("spin-full-url shall not be empty when running api with spin");

            let u = Url::parse(full_url).expect("spin-full-url should be a valid url");
            let host_and_port = match u.port() {
                Some(port) => format!("{}:{}", u.host_str().expect("spin-full-url should have host"), port),
                None => u.host_str().expect("spin-full-url should have host").to_string(),
            };
            (
                format!("{}://{}/", u.scheme(), host_and_port),
                String::from("Local Development Server"),
            )
        }
        false => {
            let host = req
                .header("x-forwarded-host")
                .expect("x-forwarded-host should be set via FWF")
                .as_str()
                .expect("x-forwarded-host shall not be empty on FWF")
                .to_string();
            (
                format!("https://{host}/"),
                String::from("Production Server"),
            )
        }
    }
}

/// Check if the application is running in the local Spin runtime
///
/// Returns true if running locally with `spin up`, false if running
/// in production (e.g., Fermyon Cloud).
fn is_local_spin_runtime(req: &Request) -> bool {
    req.header("spin-client-addr").is_some()
}

/// Serve the Swagger UI documentation interface
///
/// This function serves the interactive Swagger UI that allows users to
/// explore and test the API endpoints directly in their browser.
pub fn render_openapi_docs_ui(req: Request, _p: Params) -> anyhow::Result<impl IntoResponse> {
    let mut path = req
        .header("spin-path-info")
        .expect("spin-path-info is not present")
        .as_str()
        .unwrap_or("/")
        .to_string();

    path = path.replace("/docs/", "");

    let config = Arc::new(utoipa_swagger_ui::Config::from("openapi-description.json"));

    Ok(match utoipa_swagger_ui::serve(path.as_ref(), config) {
        Ok(swagger_file) => swagger_file
            .map(|file| {
                ResponseBuilder::new(200)
                    .header("content-type", file.content_type)
                    .body(file.bytes.to_vec())
                    .build()
            })
            .unwrap_or_else(|| Response::new(404, "Not Found")),
        Err(_) => Response::new(500, "Internal Server Error"),
    })
}

#[derive(OpenApi)]
#[openapi(
  info(
    title = "Lexodus - Federal Judicial Case Management System",
    description = "A comprehensive federal court case management system with 240+ REST endpoints built with Spin and Rust, compiled to WebAssembly.\n\n## Multi-Tenant Architecture\n\nThis system supports **all 94 federal district courts** with complete data isolation:\n\n### Tenant Identification Methods\n1. **HTTP Headers**: `X-Court-District: SDNY` or `X-Tenant-ID: sdny`\n2. **Subdomain**: `https://sdny.lexodus.gov/api/...`\n3. **Query Parameter**: `/api/cases?tenant=sdny`\n\n### Supported Federal Districts\n- **SDNY** - Southern District of New York\n- **EDNY** - Eastern District of New York\n- **CDCA** - Central District of California\n- **NDCA** - Northern District of California\n- **NDIL** - Northern District of Illinois\n- **DDC** - District of Columbia\n- ... and 88 more districts\n\n### Example Requests\n\n**Create attorney in SDNY:**\n```bash\ncurl -X POST /api/attorneys \\\n  -H 'X-Court-District: SDNY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"bar_number\": \"NY12345\", ...}'\n```\n\n**Access EDNY cases via subdomain:**\n```\nhttps://edny.lexodus.gov/api/cases\n```\n\n## Major System Modules\n- **Criminal Case Management**: Complete case lifecycle from filing through sentencing\n- **Attorney Management**: 67 endpoints for attorney, party, and representation management\n- **Judge Management**: Assignment, recusal, and workload management (26 endpoints)\n- **Docket & Calendar**: Court scheduling and document management (28 endpoints)\n- **Deadline Tracking**: FRCP compliance and Speedy Trial Act (26 endpoints)\n- **Judicial Orders**: Order creation, electronic signatures, and service tracking (18 endpoints)\n- **Judicial Opinions**: Opinion drafting, publication, and citation management (20 endpoints)\n- **Sentencing**: Federal guidelines calculations and tracking\n- **Feature Flags**: Enterprise feature management and A/B testing\n\n## Architecture\n- **Hexagonal Architecture**: Clean separation of domain and infrastructure\n- **Repository Pattern with Factory**: Multi-tenant data access layer\n- **Domain-Driven Design**: Rich domain models with business logic\n- **WebAssembly Runtime**: Fast, secure, and scalable\n- **Complete Tenant Isolation**: Each district has its own data store\n\n## Features\n- 240+ fully documented REST endpoints\n- Multi-tenant support for 94 federal districts\n- Electronic signature workflow\n- Legal citation tracking with treatment analysis\n- Comprehensive deadline and compliance management\n- Real-time statistics and analytics\n- Full OpenAPI/Swagger documentation",
    version = "5.0.0",
    license(name = "MIT"),
    contact(
      name = "Tyler Harpool",
      email = "tylerharpool@gmail.com",
      url = "https://github.com/tyler-harpool/spin-todo-api"
    )
  ),
  tags(
    (name = "todos", description = "Operations for managing ToDo items"),
    (name = "cases", description = "Criminal case management (hexagonal architecture example)"),
    (name = "monitoring", description = "Health and monitoring endpoints"),
    (name = "Judge Management", description = "Judge CRUD operations and management"),
    (name = "Judge Assignment", description = "Case assignment and workload management"),
    (name = "Judge Analytics", description = "Judge performance and workload analytics"),
    (name = "Recusal Management", description = "Recusal motion filing and processing"),
    (name = "Conflict Management", description = "Conflict of interest tracking"),
    (name = "Docket Management", description = "Docket entry creation and management"),
    (name = "Calendar Management", description = "Court calendar and event scheduling"),
    (name = "Speedy Trial Management", description = "Speedy Trial Act compliance tracking"),
    (name = "Analytics", description = "Statistical analysis and reporting"),
    (name = "Deadline Management", description = "Legal deadline tracking and monitoring"),
    (name = "Deadline Analytics", description = "Deadline compliance analysis"),
    (name = "Deadline Calculation", description = "Automated deadline calculation tools"),
    (name = "Deadline Compliance", description = "Compliance monitoring and reporting"),
    (name = "Extension Management", description = "Deadline extension requests and rulings"),
    (name = "Reminder Management", description = "Deadline reminder system"),
    (name = "Feature Management", description = "Feature flag configuration"),
    (name = "Implementation Tracking", description = "Development progress tracking"),
    (name = "Administration", description = "Multi-tenant administration"),
    (name = "Judicial Orders", description = "Court order creation, signing, and management"),
    (name = "Order Templates", description = "Order template management for standardized documents"),
    (name = "Judicial Opinions", description = "Court opinion drafting, filing, and publication"),
    (name = "Opinion Drafts", description = "Opinion draft versioning and collaboration"),
    (name = "attorneys", description = "Attorney management and registration"),
    (name = "bar-admissions", description = "Bar admission tracking and management"),
    (name = "federal-admissions", description = "Federal court admission management"),
    (name = "pro-hac-vice", description = "Pro hac vice admission tracking"),
    (name = "cja", description = "Criminal Justice Act panel and appointments"),
    (name = "ecf", description = "Electronic Court Filing system access"),
    (name = "discipline", description = "Attorney disciplinary action tracking"),
    (name = "parties", description = "Case party management"),
    (name = "representation", description = "Attorney representation tracking"),
    (name = "conflicts", description = "Conflict of interest checking"),
    (name = "process-service", description = "Legal process service and proof of delivery"),
    (name = "Sentencing", description = "Federal sentencing guidelines and calculations"),
    (name = "pdf-generation", description = "PDF document generation for court orders and filings. Supports dual response formats based on Accept header."),
    (name = "signature-management", description = "Electronic signature storage and retrieval for judge signatures"),
    (name = "Rules Engine", description = "Court rules management, including CRUD operations, filtering by category/trigger/jurisdiction, and rule evaluation (Phase 2)"),
    (name = "configuration", description = "Hierarchical configuration management for districts and judges. Supports base configuration with district and judge-level overrides."),
    (name = "Filing Pipeline", description = "Document filing pipeline with privacy scanning, rules evaluation, deadline computation, and NEF generation")
  ),
  paths(
    // ToDo API
    crate::handlers::todo::get_all,
    crate::handlers::todo::get_by_id,
    crate::handlers::todo::create_todo,
    crate::handlers::todo::toggle_by_id,
    crate::handlers::todo::delete_by_id,
    // Criminal Case API
    crate::handlers::criminal_case::create_case,
    crate::handlers::criminal_case::get_case_by_id,
    crate::handlers::criminal_case::get_case_by_number,
    crate::handlers::criminal_case::get_cases_by_judge,
    crate::handlers::criminal_case::search_cases,
    crate::handlers::criminal_case::get_case_statistics,
    crate::handlers::criminal_case::count_by_status,
    crate::handlers::criminal_case::update_case_status,
    crate::handlers::criminal_case::update_case_priority,
    crate::handlers::criminal_case::add_defendant,
    crate::handlers::criminal_case::add_evidence,
    crate::handlers::criminal_case::add_note,
    crate::handlers::criminal_case::enter_plea,
    crate::handlers::criminal_case::schedule_court_event,
    crate::handlers::criminal_case::file_motion,
    crate::handlers::criminal_case::rule_on_motion,
    crate::handlers::criminal_case::delete_case,
    crate::handlers::criminal_case::add_charge,
    // Evidence Chain of Custody
    crate::handlers::criminal_case::add_custody_transfer,
    // Docket Entries on Cases
    crate::handlers::criminal_case::add_docket_entry,
    crate::handlers::criminal_case::get_docket_entries,
    // Sealed Cases
    crate::handlers::criminal_case::seal_case,
    crate::handlers::criminal_case::unseal_case,
    // Speedy Trial Clock on Cases
    crate::handlers::criminal_case::start_speedy_trial,
    crate::handlers::criminal_case::add_case_excludable_delay,
    crate::handlers::criminal_case::get_case_speedy_trial,
    // CVRA Victims
    crate::handlers::criminal_case::add_victim,
    crate::handlers::criminal_case::get_victims,
    crate::handlers::criminal_case::send_victim_notification,
    // Judge Management API
    crate::handlers::judge::create_judge,
    crate::handlers::judge::get_all_judges,
    crate::handlers::judge::get_judge_by_id,
    crate::handlers::judge::update_judge_status,
    crate::handlers::judge::get_available_judges,
    crate::handlers::judge::assign_case,
    crate::handlers::judge::get_case_assignment,
    crate::handlers::judge::file_recusal,
    crate::handlers::judge::rule_on_recusal,
    crate::handlers::judge::get_pending_recusals,
    crate::handlers::judge::add_conflict,
    crate::handlers::judge::check_conflicts,
    crate::handlers::judge::get_workload_stats,
    crate::handlers::judge::search_judges,
    crate::handlers::judge::get_judges_by_status,
    crate::handlers::judge::get_judges_by_district,
    crate::handlers::judge::delete_judge,
    crate::handlers::judge::get_assignment_history,
    crate::handlers::judge::delete_assignment,
    crate::handlers::judge::get_recusals_by_case,
    crate::handlers::judge::get_recusals_by_judge,
    crate::handlers::judge::get_conflicts_by_judge,
    crate::handlers::judge::has_conflict,
    crate::handlers::judge::delete_conflict,
    crate::handlers::judge::get_judges_on_vacation,
    crate::handlers::judge::process_recusal,
    // Docket & Calendar API
    crate::handlers::docket::create_docket_entry,
    crate::handlers::docket::get_case_docket,
    crate::handlers::docket::get_docket_entry,
    crate::handlers::docket::add_attachment,
    crate::handlers::docket::search_docket,
    crate::handlers::docket::generate_docket_sheet,
    crate::handlers::docket::schedule_event,
    crate::handlers::docket::get_case_calendar,
    crate::handlers::docket::get_judge_schedule,
    crate::handlers::docket::update_event_status,
    crate::handlers::docket::find_available_slot,
    crate::handlers::docket::init_speedy_trial,
    crate::handlers::docket::get_speedy_trial,
    crate::handlers::docket::add_excludable_delay,
    crate::handlers::docket::get_approaching_deadlines,
    crate::handlers::docket::get_courtroom_utilization,
    crate::handlers::docket::get_entries_by_type,
    crate::handlers::docket::get_sealed_entries,
    crate::handlers::docket::search_entries,
    crate::handlers::docket::delete_entry,
    crate::handlers::docket::get_events_by_courtroom,
    crate::handlers::docket::delete_event,
    crate::handlers::docket::get_filing_statistics,
    crate::handlers::docket::get_violations,
    crate::handlers::docket::update_clock,
    crate::handlers::docket::search_calendar,
    crate::handlers::docket::check_immediate_service,
    crate::handlers::docket::check_deadline_approaching,
    // Deadline Management API
    crate::handlers::deadline::create_deadline,
    crate::handlers::deadline::get_case_deadlines,
    crate::handlers::deadline::get_deadline,
    crate::handlers::deadline::complete_deadline,
    crate::handlers::deadline::request_extension,
    crate::handlers::deadline::rule_on_extension,
    crate::handlers::deadline::get_upcoming_deadlines,
    crate::handlers::deadline::get_urgent_deadlines,
    crate::handlers::deadline::calculate_frcp_deadlines,
    crate::handlers::deadline::search_deadlines,
    crate::handlers::deadline::get_compliance_stats,
    crate::handlers::deadline::generate_compliance_report,
    crate::handlers::deadline::get_performance_metrics,
    crate::handlers::deadline::get_missed_jurisdictional,
    crate::handlers::deadline::get_pending_reminders,
    crate::handlers::deadline::send_reminders,
    crate::handlers::deadline::get_deadlines_by_type,
    crate::handlers::deadline::update_deadline_status,
    crate::handlers::deadline::delete_deadline,
    crate::handlers::deadline::get_reminders_by_deadline,
    crate::handlers::deadline::get_reminders_by_recipient,
    crate::handlers::deadline::acknowledge_reminder,
    crate::handlers::deadline::get_extension_by_id,
    crate::handlers::deadline::get_extensions_by_deadline,
    crate::handlers::deadline::get_pending_extensions,
    crate::handlers::deadline::get_federal_rules,
    // Features & Admin API
    crate::handlers::features::get_features,
    crate::handlers::features::update_feature,
    crate::handlers::features::get_implementation_status,
    crate::handlers::features::update_implementation,
    crate::handlers::features::get_blocked_features,
    crate::handlers::features::get_ready_features,
    crate::handlers::features::create_feature_manager,
    crate::handlers::features::is_feature_enabled,
    crate::handlers::features::set_feature_override,
    crate::handlers::features::clear_feature_overrides,
    crate::handlers::admin::init_tenant,
    crate::handlers::admin::get_tenant_stats,
    // Judicial Orders
    crate::handlers::order::create_order,
    crate::handlers::order::get_order,
    crate::handlers::order::update_order,
    crate::handlers::order::delete_order,
    crate::handlers::order::list_orders,
    crate::handlers::order::sign_order,
    crate::handlers::order::issue_order,
    crate::handlers::order::add_service_record,
    crate::handlers::order::get_orders_by_case,
    crate::handlers::order::get_orders_by_judge,
    crate::handlers::order::get_pending_signatures,
    crate::handlers::order::get_expiring_orders,
    crate::handlers::order::get_order_statistics,
    crate::handlers::order::create_from_template,
    crate::handlers::order::create_template,
    crate::handlers::order::get_template,
    crate::handlers::order::list_templates,
    // Judicial Opinions
    crate::handlers::opinion::create_opinion,
    crate::handlers::opinion::get_opinion,
    crate::handlers::opinion::update_opinion,
    crate::handlers::opinion::delete_opinion,
    crate::handlers::opinion::list_opinions,
    crate::handlers::opinion::file_opinion,
    crate::handlers::opinion::publish_opinion,
    crate::handlers::opinion::add_judge_vote,
    crate::handlers::opinion::add_citation,
    crate::handlers::opinion::add_headnote,
    crate::handlers::opinion::get_opinions_by_case,
    crate::handlers::opinion::get_opinions_by_author,
    crate::handlers::opinion::search_opinions,
    crate::handlers::opinion::get_precedential_opinions,
    crate::handlers::opinion::get_opinion_statistics,
    crate::handlers::opinion::get_citation_statistics,
    crate::handlers::opinion::create_draft,
    crate::handlers::opinion::get_drafts,
    crate::handlers::opinion::get_current_draft,
    crate::handlers::opinion::is_majority_opinion,
    crate::handlers::opinion::is_binding_opinion,
    crate::handlers::opinion::calculate_opinion_statistics,
    crate::handlers::opinion::add_draft_comment,
    crate::handlers::opinion::resolve_draft_comment,
    // Federal Sentencing API
    crate::handlers::sentencing::create_sentencing,
    crate::handlers::sentencing::get_sentencing,
    crate::handlers::sentencing::update_sentencing,
    crate::handlers::sentencing::delete_sentencing,
    crate::handlers::sentencing::find_by_case,
    crate::handlers::sentencing::find_by_defendant,
    crate::handlers::sentencing::find_by_judge,
    crate::handlers::sentencing::find_pending,
    crate::handlers::sentencing::calculate_guidelines,
    crate::handlers::sentencing::get_departure_stats,
    crate::handlers::sentencing::get_variance_stats,
    crate::handlers::sentencing::add_departure,
    crate::handlers::sentencing::add_variance,
    crate::handlers::sentencing::get_substantial_assistance,
    crate::handlers::sentencing::add_special_condition,
    crate::handlers::sentencing::update_supervised_release,
    crate::handlers::sentencing::find_active_supervision,
    crate::handlers::sentencing::add_bop_designation,
    crate::handlers::sentencing::get_rdap_eligible,
    crate::handlers::sentencing::get_judge_stats,
    crate::handlers::sentencing::get_district_stats,
    crate::handlers::sentencing::get_trial_penalty,
    crate::handlers::sentencing::add_prior_sentence,
    crate::handlers::sentencing::find_upcoming,
    crate::handlers::sentencing::find_appeal_deadlines,
    crate::handlers::sentencing::find_by_date_range,
    crate::handlers::sentencing::get_offense_type_stats,
    crate::handlers::sentencing::calculate_criminal_history_points,
    crate::handlers::sentencing::calculate_offense_level,
    crate::handlers::sentencing::lookup_guidelines_range,
    crate::handlers::sentencing::check_safety_valve_eligible,
    // Rules Engine API
    crate::handlers::rules::create_rule,
    crate::handlers::rules::list_rules,
    crate::handlers::rules::get_rules_by_category,
    crate::handlers::rules::get_rules_by_trigger,
    crate::handlers::rules::get_active_rules_for_jurisdiction,
    crate::handlers::rules::evaluate_rules,
    crate::handlers::rules::get_rule,
    crate::handlers::rules::update_rule,
    crate::handlers::rules::delete_rule,
    // PDF Generation API (Hexagonal Architecture)
    crate::handlers::pdf_hexagonal::generate_rule16b,
    crate::handlers::pdf_hexagonal::generate_signed_rule16b,
    crate::handlers::pdf_hexagonal::generate_court_order,
    crate::handlers::pdf_hexagonal::generate_minute_entry,
    crate::handlers::pdf_hexagonal::generate_waiver_indictment,
    crate::handlers::pdf_hexagonal::generate_conditions_release,
    crate::handlers::pdf_hexagonal::generate_criminal_judgment,
    crate::handlers::pdf_hexagonal::generate_batch_pdfs,
    crate::handlers::pdf_hexagonal::store_signature,
    crate::handlers::pdf_hexagonal::get_signature,
    // Attorney Management API
    crate::handlers::attorney::create_attorney,
    crate::handlers::attorney::get_attorney,
    crate::handlers::attorney::get_attorney_by_bar_number,
    crate::handlers::attorney::update_attorney,
    crate::handlers::attorney::delete_attorney,
    crate::handlers::attorney::list_attorneys,
    crate::handlers::attorney::search_attorneys,
    crate::handlers::attorney::get_attorneys_by_status,
    crate::handlers::attorney::get_attorneys_by_firm,
    crate::handlers::attorney::add_bar_admission,
    crate::handlers::attorney::remove_bar_admission,
    crate::handlers::attorney::get_attorneys_by_bar_state,
    crate::handlers::attorney::add_federal_admission,
    crate::handlers::attorney::remove_federal_admission,
    crate::handlers::attorney::get_attorneys_admitted_to_court,
    crate::handlers::attorney::add_pro_hac_vice,
    crate::handlers::attorney::update_pro_hac_vice_status,
    crate::handlers::attorney::get_active_pro_hac_vice,
    crate::handlers::attorney::get_pro_hac_vice_by_case,
    crate::handlers::attorney::add_to_cja_panel,
    crate::handlers::attorney::remove_from_cja_panel,
    crate::handlers::attorney::get_cja_panel_attorneys,
    crate::handlers::attorney::add_cja_appointment,
    crate::handlers::attorney::get_cja_appointments,
    crate::handlers::attorney::get_pending_cja_vouchers,
    crate::handlers::attorney::update_ecf_registration,
    crate::handlers::attorney::check_good_standing,
    crate::handlers::attorney::check_federal_practice,
    crate::handlers::attorney::check_ecf_privileges,
    crate::handlers::attorney::calculate_attorney_win_rate,
    crate::handlers::attorney::get_attorneys_with_ecf,
    crate::handlers::attorney::revoke_ecf_access,
    crate::handlers::attorney::add_disciplinary_action,
    crate::handlers::attorney::get_disciplinary_history,
    crate::handlers::attorney::get_attorneys_with_discipline,
    // Party Management API
    crate::handlers::attorney::create_party,
    crate::handlers::attorney::get_party,
    crate::handlers::attorney::update_party,
    crate::handlers::attorney::delete_party,
    crate::handlers::attorney::list_parties_by_case,
    crate::handlers::attorney::list_parties_by_attorney,
    crate::handlers::attorney::update_party_status,
    crate::handlers::attorney::check_party_needs_service,
    crate::handlers::attorney::get_party_lead_counsel,
    crate::handlers::attorney::check_party_represented,
    crate::handlers::attorney::get_unrepresented_parties,
    // Representation API
    crate::handlers::attorney::add_representation,
    crate::handlers::attorney::get_representation,
    crate::handlers::attorney::end_representation,
    crate::handlers::attorney::substitute_attorney,
    crate::handlers::attorney::get_case_representations,
    crate::handlers::attorney::get_active_representations,
    crate::handlers::attorney::migrate_representations,
    // Conflict Management API
    crate::handlers::attorney::create_conflict_check,
    crate::handlers::attorney::get_attorney_conflicts,
    crate::handlers::attorney::check_party_conflicts,
    crate::handlers::attorney::clear_conflict,
    // Service Management API
    crate::handlers::attorney::create_service_record,
    crate::handlers::attorney::get_service_by_document,
    crate::handlers::attorney::get_service_by_party,
    crate::handlers::attorney::mark_service_completed,
    crate::handlers::attorney::bulk_update_status,
    crate::handlers::attorney::bulk_add_to_service,
    // Attorney Performance API
    crate::handlers::attorney::get_attorney_case_count,
    crate::handlers::attorney::get_attorney_win_rate,
    crate::handlers::attorney::get_attorney_metrics,
    crate::handlers::attorney::get_top_attorneys,
    // Configuration Management API
    crate::handlers::config::get_config,
    crate::handlers::config::get_district_overrides,
    crate::handlers::config::get_judge_overrides,
    crate::handlers::config::update_district_config,
    crate::handlers::config::update_judge_config,
    crate::handlers::config::clear_district_overrides,
    crate::handlers::config::clear_judge_overrides,
    crate::handlers::config::preview_config,
    // Filing Pipeline API
    crate::handlers::filing::submit_filing,
    crate::handlers::filing::validate_filing,
    crate::handlers::filing::list_jurisdictions,
    // Health Monitoring
    crate::handlers::health::health_check,
  ),
  components(
    schemas(
      // ToDo Models
      crate::domain::ToDo,
      crate::handlers::todo::ToDoModel,
      crate::handlers::todo::CreateToDoModel,
      crate::handlers::todo::PaginatedResponse<crate::handlers::todo::ToDoModel>,
      crate::handlers::todo::PaginationParams,
      // Criminal Case Models
      crate::handlers::criminal_case::CreateCaseRequest,
      crate::handlers::criminal_case::CaseResponse,
      crate::handlers::criminal_case::CaseSearchResponse,
      crate::handlers::criminal_case::UpdateStatusRequest,
      crate::handlers::criminal_case::UpdatePriorityRequest,
      crate::handlers::criminal_case::AddDefendantRequest,
      crate::handlers::criminal_case::AddEvidenceRequest,
      crate::handlers::criminal_case::AddNoteRequest,
      crate::handlers::criminal_case::EnterPleaRequest,
      crate::handlers::criminal_case::ScheduleEventRequest,
      crate::handlers::criminal_case::FileMotionRequest,
      crate::handlers::criminal_case::RuleOnMotionRequest,
      crate::handlers::criminal_case::CountResponse,
      crate::handlers::criminal_case::DefendantResponse,
      crate::handlers::criminal_case::AddChargeRequest,
      crate::handlers::criminal_case::AddCustodyTransferRequest,
      crate::handlers::criminal_case::EvidenceResponse,
      crate::handlers::criminal_case::DocketEntryResponse,
      crate::domain::criminal_case::EvidenceType,
      crate::domain::criminal_case::EvidenceCondition,
      crate::domain::criminal_case::Evidence,
      crate::domain::criminal_case::CustodyTransfer,
      crate::handlers::criminal_case::SpeedyTrialStatusResponse,
      crate::handlers::criminal_case::VictimResponse,
      crate::handlers::criminal_case::AddDocketEntryRequest,
      crate::handlers::criminal_case::SealCaseRequest,
      crate::handlers::criminal_case::UnsealCaseRequest,
      crate::handlers::criminal_case::StartSpeedyTrialRequest,
      crate::handlers::criminal_case::AddCaseExcludableDelayRequest,
      crate::handlers::criminal_case::AddVictimRequest,
      crate::handlers::criminal_case::SendVictimNotificationRequest,
      // Victim domain types
      crate::domain::victim::Victim,
      crate::domain::victim::VictimType,
      crate::domain::victim::NotificationMethod,
      crate::domain::victim::NotificationType,
      crate::domain::victim::VictimNotification,
      crate::domain::victim::NotificationPreferences,
      crate::domain::criminal_case::CaseStatus,
      crate::domain::criminal_case::CasePriority,
      crate::domain::criminal_case::CrimeType,
      crate::domain::criminal_case::EventType,
      crate::domain::criminal_case::MotionType,
      crate::domain::criminal_case::CriminalCase,
      crate::domain::criminal_case::CaseNote,
      crate::domain::criminal_case::CourtEvent,
      crate::domain::criminal_case::Motion,
      crate::domain::defendant::Defendant,
      crate::domain::defendant::Count,
      crate::domain::defendant::BondInfo,
      crate::domain::defendant::BailType,
      crate::domain::defendant::CustodyStatus,
      crate::domain::defendant::CitizenshipStatus,
      crate::domain::defendant::PleaType,
      crate::domain::defendant::Verdict,
      crate::domain::defendant::CreateDefendantRequest,
      crate::domain::defendant::AddCountRequest,
      crate::domain::common::MotionStatus,
      crate::ports::case_repository::CaseStatistics,
      // Judge Management Models
      crate::handlers::judge::CreateJudgeRequest,
      crate::handlers::judge::UpdateJudgeStatusRequest,
      crate::handlers::judge::AssignCaseRequest,
      crate::handlers::judge::FileRecusalRequest,
      crate::handlers::judge::RuleOnRecusalRequest,
      crate::handlers::judge::AddConflictRequest,
      crate::handlers::judge::WorkloadResponse,
      crate::domain::judge::Judge,
      crate::domain::judge::JudgeTitle,
      crate::domain::judge::JudgeStatus,
      crate::domain::judge::CaseAssignment,
      crate::domain::judge::RecusalMotion,
      crate::domain::judge::ConflictOfInterest,
      crate::domain::judge::JudgeConflictType,
      crate::domain::judge::RecusalReason,
      crate::domain::judge::RecusalStatus,
      crate::domain::judge::AssignmentType,
      crate::domain::judge::CaseType,
      // Docket & Calendar Models
      crate::handlers::docket::CreateDocketEntryRequest,
      crate::handlers::docket::AddAttachmentRequest,
      crate::handlers::docket::ScheduleEventRequest,
      crate::handlers::docket::UpdateEventStatusRequest,
      crate::handlers::docket::AddExcludableDelayRequest,
      crate::handlers::docket::FilingStatsResponse,
      crate::domain::docket::DocketEntry,
      crate::domain::docket::DocketEntryType,
      crate::domain::docket::DocketAttachment,
      crate::domain::docket::CalendarEntry,
      crate::domain::docket::CalendarEventType,
      crate::domain::docket::EventStatus,
      crate::domain::docket::SpeedyTrialClock,
      crate::domain::docket::ExcludableDelay,
      crate::domain::docket::DelayReason,
      // Deadline Management Models
      crate::handlers::deadline::CreateDeadlineRequest,
      crate::handlers::deadline::RequestExtensionRequest,
      crate::handlers::deadline::RuleOnExtensionRequest,
      crate::handlers::deadline::CalculateDeadlinesRequest,
      crate::handlers::deadline::ComplianceStatsResponse,
      crate::domain::deadline::Deadline,
      crate::domain::deadline::DeadlineType,
      crate::domain::deadline::DeadlineStatus,
      crate::domain::deadline::ExtensionRequest,
      crate::domain::deadline::ExtensionStatus,
      crate::domain::deadline::FederalRule,
      crate::domain::deadline::DeadlineReminder,
      // Feature Management Models
      crate::handlers::features::FeaturesResponse,
      crate::handlers::features::UpdateFeaturesRequest,
      crate::domain::features::FeatureManager,
      crate::domain::features::JudicialFeatures,
      crate::domain::features::ImplementationTracker,
      crate::domain::features::FeatureStatus,
      crate::domain::features::ImplementationStatus,
      // Internal Request/Response Types
      crate::handlers::deadline::StatusUpdate,
      crate::handlers::docket::InitSpeedyTrialRequest,
      crate::handlers::docket::SearchResponse,
      crate::handlers::docket::AvailableSlotResponse,
      crate::handlers::docket::CalendarSearchResponse,
      crate::handlers::features::UpdateRequest,
      crate::handlers::features::OverrideRequest,
      crate::handlers::judge::ProcessRequest,
      crate::handlers::judge::ConflictCheckResponse,
      crate::handlers::judge::SearchResponse,
      crate::handlers::deadline::SearchResponse,
      crate::handlers::deadline::ReminderResponse,
      crate::handlers::deadline::PendingExtensionsResponse,
      // Judicial Order Models
      crate::domain::order::JudicialOrder,
      crate::domain::order::OrderType,
      crate::domain::order::OrderStatus,
      crate::domain::common::ElectronicSignature,
      crate::domain::order::ServiceRecord,
      // ServiceMethod and ServiceStatus already registered from common module above
      crate::domain::order::OrderMetadata,
      crate::domain::order::OrderTemplate,
      crate::domain::order::TemplateVariable,
      crate::domain::order::VariableType,
      crate::handlers::order::CreateOrderRequest,
      crate::handlers::order::UpdateOrderRequest,
      crate::handlers::order::SignOrderRequest,
      crate::handlers::order::AddServiceRequest,
      crate::handlers::order::CreateFromTemplateRequest,
      crate::handlers::order::CreateTemplateRequest,
      crate::handlers::order::OrderListResponse,
      crate::ports::document_repository::OrderFilter,
      crate::ports::document_repository::OrderStatistics,
      // Judicial Opinion Models
      crate::domain::opinion::JudicialOpinion,
      crate::domain::opinion::OpinionType,
      crate::domain::opinion::OpinionStatus,
      crate::domain::opinion::Disposition,
      crate::domain::opinion::Citation,
      crate::domain::opinion::JudgeVote,
      crate::domain::opinion::VoteType,
      crate::domain::opinion::RelatedOpinion,
      crate::domain::opinion::OpinionRelationship,
      crate::domain::opinion::LegalCitation,
      crate::domain::opinion::CitationTreatment,
      crate::domain::opinion::Headnote,
      crate::domain::opinion::OpinionDraft,
      crate::domain::opinion::DraftComment,
      crate::domain::opinion::OpinionStatistics,
      crate::handlers::opinion::CreateOpinionRequest,
      crate::handlers::opinion::UpdateOpinionRequest,
      crate::handlers::opinion::PublishOpinionRequest,
      crate::handlers::opinion::AddVoteRequest,
      crate::handlers::opinion::AddCitationRequest,
      crate::handlers::opinion::AddHeadnoteRequest,
      crate::handlers::opinion::CreateDraftRequest,
      crate::handlers::opinion::AddCommentRequest,
      crate::handlers::opinion::OpinionListResponse,
      crate::ports::document_repository::OpinionFilter,
      crate::ports::document_repository::OpinionStatistics,
      crate::ports::document_repository::CitationStatistics,
      crate::ports::document_repository::CaseCitation,
      crate::ports::document_repository::CitationTrend,
      // Federal Sentencing Models
      crate::domain::sentencing::Sentencing,
      crate::domain::sentencing::CreateSentencingRequest,
      crate::domain::sentencing::GuidelinesRange,
      crate::domain::sentencing::Departure,
      crate::domain::sentencing::DepartureType,
      crate::domain::sentencing::Variance,
      crate::domain::sentencing::VarianceType,
      crate::domain::sentencing::PriorConviction,
      crate::domain::sentencing::CriminalHistoryCategory,
      crate::domain::sentencing::SupervisedRelease,
      crate::domain::sentencing::SpecialCondition,
      crate::domain::sentencing::BOPDesignation,
      crate::domain::sentencing::FacilityLevel,
      crate::domain::sentencing::Restitution,
      crate::domain::sentencing::SubstantialAssistance,
      crate::domain::sentencing::ConsecutiveSentence,
      crate::domain::sentencing::PriorSentence,
      // Attorney & Party Models
      crate::domain::attorney::Attorney,
      crate::domain::attorney::CreateAttorneyRequest,
      crate::domain::attorney::AttorneyStatus,
      crate::domain::attorney::Address,
      crate::domain::attorney::BarAdmission,
      crate::domain::attorney::AdmissionStatus,
      crate::domain::attorney::FederalAdmission,
      crate::domain::attorney::ProHacViceAdmission,
      crate::domain::attorney::ProHacViceStatus,
      crate::domain::attorney::ECFRegistration,
      crate::domain::attorney::CJAAppointment,
      crate::domain::attorney::VoucherStatus,
      crate::domain::attorney::CompensationStatus,
      crate::domain::attorney::DisciplinaryAction,
      crate::domain::attorney::DisciplineType,
      crate::domain::attorney::DisciplineStatus,
      crate::domain::attorney::Party,
      crate::domain::attorney::CreatePartyRequest,
      crate::domain::attorney::PartyType,
      crate::domain::attorney::PartyRole,
      crate::domain::attorney::EntityType,
      crate::domain::attorney::PartyStatus,
      crate::domain::attorney::AttorneyRepresentation,
      crate::domain::attorney::RepresentationType,
      crate::domain::attorney::RepresentationStatus,
      crate::domain::attorney::WithdrawalReason,
      crate::domain::attorney::Representation,
      crate::domain::attorney::Conflict,
      crate::domain::common::ConflictType,
      crate::domain::common::ConflictSeverity,
      crate::domain::attorney::ConflictResult,
      crate::domain::attorney::ServiceRecord,
      crate::domain::common::ServiceMethod,
      crate::domain::common::ServiceStatus,
      crate::handlers::attorney::WinRateRequest,
      // PDF Generation Models (Hexagonal Architecture)
      crate::handlers::pdf_hexagonal::Rule16bRequest,
      crate::handlers::pdf_hexagonal::CourtOrderRequest,
      crate::handlers::pdf_hexagonal::MinuteEntryRequest,
      crate::handlers::pdf_hexagonal::WaiverIndictmentRequest,
      crate::handlers::pdf_hexagonal::ConditionsReleaseRequest,
      crate::handlers::pdf_hexagonal::CriminalJudgmentRequest,
      crate::handlers::pdf_hexagonal::PdfResponse,
      crate::handlers::pdf_hexagonal::BatchPdfRequest,
      crate::handlers::pdf_hexagonal::BatchPdfResponse,
      crate::handlers::pdf_hexagonal::DocumentRequestDto,
      crate::handlers::pdf_hexagonal::StoreSignatureRequest,
      // Configuration Models
      crate::domain::config::Configuration,
      crate::domain::config::ConfigOverride,
      crate::domain::config::ConfigResponse,
      crate::domain::config::ConfigMetadata,
      // Rules Engine Models
      crate::domain::rule::Rule,
      crate::domain::rule::RuleSource,
      crate::domain::rule::RuleCategory,
      crate::domain::rule::TriggerEvent,
      crate::domain::rule::RuleAction,
      crate::domain::rule::RulePriority,
      crate::domain::rule::RuleStatus,
      crate::domain::rule::RuleCondition,
      crate::domain::rule::CreateRuleRequest,
      crate::domain::rule::UpdateRuleRequest,
      crate::domain::rule::ComplianceResult,
      crate::handlers::rules::RuleSearchResponse,
      crate::handlers::rules::EvaluateRulesRequest,
      crate::handlers::rules::EvaluateRulesResponse,
      // Filing Pipeline Models
      crate::domain::filing_pipeline::FilingSubmission,
      crate::domain::filing_pipeline::FilingContext,
      crate::domain::filing_pipeline::ComplianceReport,
      crate::domain::filing_pipeline::RuleResult,
      crate::domain::filing_pipeline::FilingReceipt,
      crate::domain::nef::NoticeOfElectronicFiling,
      crate::domain::nef::NefRecipient,
      crate::domain::nef::DeliveryMethod,
      crate::domain::privacy::PrivacyScanResult,
      crate::domain::privacy::PiiMatch,
      crate::domain::privacy::PiiType,
      crate::domain::privacy::RestrictedDocType,
      crate::domain::deadline_calc::DeadlineComputeRequest,
      crate::domain::deadline_calc::DeadlineResult,
      crate::domain::deadline_calc::ServiceMethod,
      crate::domain::deadline_calc::FederalHoliday,
      crate::handlers::filing::JurisdictionListResponse,
      crate::handlers::filing::ValidationResponse,
      crate::handlers::criminal_case::CreateCaseWithComplianceResponse,
      // Health & Error Models
      crate::handlers::health::HealthStatus,
      crate::error::ErrorResponse,
    )
  )
)]
struct OpenApiDocs {}
